import Providers from "@/lib/Providers";
import "./globals.css";
import { Montserrat } from "next/font/google";
import type { Metadata } from "next";

// const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Handyman Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={montserrat.className}>{children}</body>
      </html>
    </Providers>
  );
}
